name: Build LittleKernel for Samsung Galaxy S5 Mini Duos (G800H)
on: [push]
jobs:
  Build-LittleKernel-All:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt install make gcc-arm-none-eabi
      - name: Check out LK
        uses: actions/checkout@v2
      - run: make -j$(nproc) msm8226
      - name: Upload msm8226 lk.bin
        uses: actions/upload-artifact@v2
        with:
          name: lk.bin
          path: build-msm8226/lk.bin
